<?php

namespace ContainerJoVkQbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MxSmC0UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mxSmC0U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mxSmC0U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', true],
            'updateBook' => ['privates', '.errored..service_locator.mxSmC0U.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.mxSmC0U": it references class "App\\Entity\\Book" but no such service exists.'],
        ], [
            'authorRepository' => 'App\\Repository\\AuthorRepository',
            'bookRepository' => 'App\\Repository\\BookRepository',
            'entityManagerInterface' => '?',
            'serializerInterface' => '?',
            'updateBook' => 'App\\Entity\\Book',
        ]);
    }
}
