<?php

namespace ContainerJoVkQbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YM96oCLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YM96oCL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YM96oCL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'author' => ['privates', '.errored..service_locator.YM96oCL.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.YM96oCL": it references class "App\\Entity\\Author" but no such service exists.'],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'author' => 'App\\Entity\\Author',
            'entityManagerInterface' => '?',
            'serializerInterface' => '?',
        ]);
    }
}
