<?php

namespace ContainerJoVkQbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBook3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mxSmC0U.App\Entity\Book' shared service.
     *
     * @return \App\Entity\Book
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mxSmC0U": it references class "App\\Entity\\Book" but no such service exists.');
    }
}
