<?php

namespace ContainerXuvnHPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_30Gku0KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.30Gku0K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.30Gku0K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'authorRepository' => 'App\\Repository\\AuthorRepository',
            'serializerInterface' => '?',
        ]);
    }
}
