<?php

namespace ContainerXuvnHPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2cXF24xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2cXF24x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2cXF24x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'author' => ['privates', '.errored..service_locator.2cXF24x.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.2cXF24x": it references class "App\\Entity\\Author" but no such service exists.'],
            'book' => ['privates', '.errored..service_locator.2cXF24x.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.2cXF24x": it references class "App\\Entity\\Book" but no such service exists.'],
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'author' => 'App\\Entity\\Author',
            'book' => 'App\\Entity\\Book',
            'serializerInterface' => '?',
        ]);
    }
}
