<?php

namespace ContainerXuvnHPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MM9QlU2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mM9QlU2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mM9QlU2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'author' => ['privates', '.errored..service_locator.mM9QlU2.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.mM9QlU2": it references class "App\\Entity\\Author" but no such service exists.'],
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'author' => 'App\\Entity\\Author',
            'serializerInterface' => '?',
        ]);
    }
}
