<?php

namespace ContainerXuvnHPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3_XP5W1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3.XP5W1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3.XP5W1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'book' => ['privates', '.errored..service_locator.3.XP5W1.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.3.XP5W1": it references class "App\\Entity\\Book" but no such service exists.'],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'entityManagerInterface' => '?',
        ]);
    }
}
