<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJoVkQbP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJoVkQbP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJoVkQbP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJoVkQbP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJoVkQbP\App_KernelDevDebugContainer([
    'container.build_hash' => 'JoVkQbP',
    'container.build_id' => 'a6c48a95',
    'container.build_time' => 1662031259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJoVkQbP');
